export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const SAVE_IN_PROGRESS = 'SAVE_IN_PROGRESS';
export const FETCH_IN_PROGRESS = 'FETCH_IN_PROGRESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';